
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int SEMICOLON = 3;
  public static final int ELSE = 14;
  public static final int PLUS = 9;
  public static final int THEN = 16;
  public static final int IDENTIFIER = 17;
  public static final int IF = 13;
  public static final int COMMA = 2;
  public static final int LESSTHAN = 7;
  public static final int EOF = 0;
  public static final int MULT = 10;
  public static final int DEF = 15;
  public static final int DIV = 11;
  public static final int MORETHAN = 6;
  public static final int MINUS = 8;
  public static final int error = 1;
  public static final int INTEGER = 18;
  public static final int ASSIGNMENT = 12;
  public static final int RIGHTPAREN = 5;
  public static final int LEFTPAREN = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "SEMICOLON",
  "LEFTPAREN",
  "RIGHTPAREN",
  "MORETHAN",
  "LESSTHAN",
  "MINUS",
  "PLUS",
  "MULT",
  "DIV",
  "ASSIGNMENT",
  "IF",
  "ELSE",
  "DEF",
  "THEN",
  "IDENTIFIER",
  "INTEGER"
  };
}

